data_root: "/home/jingwen/data/tum_rgbd/rgbd_dataset_freiburg1_xyz"
data_type: "fr1"
near: 0.1
far: 5.0
vol_bounds: [-2.5, 1.5, -2., 2.5, -0.2, 1.5]
voxel_size: 0.04
n_pyramids: 3
n_iters: [6, 3, 3]
dampings: [1.0e-4, 1.0e-4, 1.0e-2]
n_steps: 192