data_root: "/home/jingwen/data/tum_rgbd/rgbd_dataset_freiburg3_long_office_household"
data_type: "fr3"
near: 0.1
far: 4.0
vol_bounds: [-2.5, 1.0, -1.5, 1.5, -0.2, 1.8]
voxel_size: 0.025
n_pyramids: 3
n_iters: [6, 3, 3]
dampings: [1.0e-4, 1.0e-4, 1.0e-2]
n_steps: 192
